### ISSUE TITLE
ProductPageView Pixel issue

### ISSUE THREAD

**Issue by paulmesa-aloyoga** [bloomreach/discovery-ios-sdk#23]
https://github.com/bloomreach/discovery-ios-sdk/blob/bb9c1ae6e4901b41a6aa53023ff84e0f564b362f/Sources/discovery-ios-sdk/pixel/processpixel/PageViewPixelFormatter.swift#L20

This line looks to be pulling out the same var from the object as the line before it.

**Comment by prashant-br** [comment]
The issue has been fixed
