### ISSUE TITLE
Category Page View Pixel issue

### ISSUE THREAD

**Issue by paulmesa-aloyoga** [bloomreach/discovery-ios-sdk#27]
When triggering a category page view, I'm receiving the following error
```
cat_id: 
Description: This field is required
```
The debug print of the event is as follows with some info redacted
```
pix_request_domain: p.brsrvr.com
debug: true
merchant: XXX
ptype: category
type: pageview
title: XXXXX
url: XXXXX
cookie2:XXXX
rand: XXXX
catId: XXX
ref: XXXX
user_id: XXX
test_data: true
cat: XXX
```

catId is populated yet we receive an error.

Based on the code here https://github.com/bloomreach/discovery-ios-sdk/blob/933e1e0c21ef763c52c8de3245d7b566ed0c2543/Sources/discovery-ios-sdk/api/request/WidgetRequest.swift#L78. I believe the field name is incorrect in the sdk here https://github.com/bloomreach/discovery-ios-sdk/blob/933e1e0c21ef763c52c8de3245d7b566ed0c2543/Sources/discovery-ios-sdk/pixel/processpixel/PageViewPixelFormatter.swift#L86

**Comment by prashant-br** [comment]
The issue has been fixed
