### ISSUE TITLE
First Process Event is sent for every pixel

### ISSUE THREAD

**Issue by paulmesa-aloyoga** [bloomreach/discovery-ios-sdk#29]
When an item is processed and is supposed to be sent, the SDK continues to just send the head of the queue rather than sending the head and then removing the sent element.

This takes the head element https://github.com/bloomreach/discovery-ios-sdk/blob/main/Sources/discovery-ios-sdk/pixel/processpixel/PixelProcessor.swift#L24 but the head element is never removed anywhere after that so the same event is sent repeatedly.

**Comment by prashant-br** [comment]
The issue has been fixed.
